language: go
go:
- 1.13.x
env:
- IMAGE_NAME=thorsager/go-direct

services:
- docker

script:
- make test
- make

deploy:
  script:
  - ./scripts/docker_build.sh -n "${TRAVIS_BUILD_ID}"
  - ./scripts/docker_tag.sh -s "${TRAVIS_BUIL_ID}" -t "${IMAGE_NAME}/${TRAVIS_BRANCH}"
  - ./scripts/docker_login.sh
  - docker push "${IMAGE_NAME}/${TRAVIS_BRANCH}"
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH != master 

