language: go
go:
- 1.13.x

services:
- docker

script:
- make test
- make

deploy:
  script:
  - docker build -t ${TRAVIS_BUILD_ID} .
  - docker tag ${TRAVIS_BILD_ID} thorsager/go-direct:${TRAVIS_BRANCH}
  - echo "${REGISTRY_PASSWORD}" | docker login -u "$REGISTRY_USERNAME" --password-stdin
  - docker push thorsager/go-direct:${TRAVIS_BRANCH}
  on:
	tags: true

